Pokemon.create(name: 'フシギバナ', image: 'venusaur_license.png', attack_type: 1, role: 0, attack_category: 1)
Pokemon.create(name: 'リザードン', image: 'charizard_license.png', attack_type: 0, role: 3, attack_category: 0)
Pokemon.create(name: 'カメックス', image: 'blastoise_license.png', attack_type: 1, role: 1, attack_category: 1)
Pokemon.create(name: 'ピカチュウ', image: 'pikachu_license.png', attack_type: 1, role: 0, attack_category: 1)
Pokemon.create(name: 'アローラキュウコン', image: 'alolan-ninetales_license.png', attack_type: 1, role: 0, attack_category: 1)
Pokemon.create(name: 'プクリン', image: 'wigglytuff_license.png', attack_type: 0, role: 4, attack_category: 1)
Pokemon.create(name: 'カイリキー', image: 'machamp_license.png', attack_type: 0, role: 3, attack_category: 0)
Pokemon.create(name: 'ヤドラン', image: 'slowbro_license.png', attack_type: 1, role: 1, attack_category: 1)
Pokemon.create(name: 'ゲンガー', image: 'gengar_license.png', attack_type: 0, role: 2, attack_category: 1)
Pokemon.create(name: 'バリヤード', image: 'mr-mime_license.png', attack_type: 0, role: 4, attack_category: 1)
Pokemon.create(name: 'カビゴン', image: 'snorlax_license.png', attack_type: 0, role: 1, attack_category: 0)
Pokemon.create(name: 'ハピナス', image: 'blissey_license.png', attack_type: 0, role: 4, attack_category: 1)
Pokemon.create(name: 'サーナイト', image: 'gardevoir_license.png', attack_type: 1, role: 0, attack_category: 1)
Pokemon.create(name: 'アブソル', image: 'absol_license.png', attack_type: 0, role: 2, attack_category: 0)
Pokemon.create(name: 'ガブリアス', image: 'garchomp_license.png', attack_type: 0, role: 3, attack_category: 0)
Pokemon.create(name: 'ルカリオ', image: 'lucario_license.png', attack_type: 0, role: 3, attack_category: 0)
Pokemon.create(name: 'イワパレス', image: 'crustle_license.png', attack_type: 0, role: 1, attack_category: 0)
Pokemon.create(name: 'ゲッコウガ', image: 'greninja_license.png', attack_type: 1, role: 0, attack_category: 0)
Pokemon.create(name: 'ファイアロー', image: 'talonflame_license.png', attack_type: 0, role: 2, attack_category: 0)
Pokemon.create(name: 'ゼラオラ', image: 'zeraora_license.png', attack_type: 0, role: 2, attack_category: 0)
Pokemon.create(name: 'エースバーン', image: 'cinderace_license.png', attack_type: 1, role: 0, attack_category: 0)
Pokemon.create(name: 'ワタシラガ', image: 'eldegoss_license.png', attack_type: 1, role: 4, attack_category: 1)
Pokemon.create(name: 'ウッウ', image: 'cramorant_license.png', attack_type: 1, role: 0, attack_category: 1)
Pokemon.create(name: 'マンムー', image: 'mamoswine_license.png', attack_type: 0, role: 1, attack_category: 0)
Pokemon.create(name: 'ニンフィア', image: 'sylveon_license.png', attack_type: 1, role: 0, attack_category: 1)
Pokemon.create(name: 'ヨクバリス', image: 'greedent_license.png', attack_type: 0, role: 1, attack_category: 0)

Stage.create(name: 'レモータスタジアム', image: 'remoat_stadium.jpg')
Stage.create(name: 'ジーヴルシティ', image: 'shivre_city.jpg')
Stage.create(name: 'マールスタジアム', image: 'mer_stadium.jpg')
Stage.create(name: 'ゼフィオパーク', image: 'auroma_park.jpg')

BattleItem.create(name: 'キズぐすり', image: 'battle_item_1.png')
BattleItem.create(name: 'プラスパワー', image: 'battle_item_2.png')
BattleItem.create(name: 'スピーダー', image: 'battle_item_3.png')
BattleItem.create(name: 'エネコのしっぽ', image: 'battle_item_4.png')
BattleItem.create(name: 'だっしゅつボタン', image: 'battle_item_5.png')
BattleItem.create(name: 'どんそくスモーク', image: 'battle_item_6.png')
BattleItem.create(name: 'なんでもなおし', image: 'battle_item_7.png')
BattleItem.create(name: 'ゴールかそくそうち', image: 'battle_item_8.png')

Tool.create(name: 'ちからのハチマキ', image: 'tool_01.png')
Tool.create(name: 'かいがらのすず', image: 'tool_02.png')
Tool.create(name: 'エナジーアンプ', image: 'tool_03.png')
Tool.create(name: 'かるいし', image: 'tool_04.png')
Tool.create(name: 'おたすけバリア', image: 'tool_05.png')
Tool.create(name: 'ゴールサポーター', image: 'tool_06.png')
Tool.create(name: 'がくしゅうそうち', image: 'tool_07.png')
Tool.create(name: 'とつげきチョッキ', image: 'tool_08.png')
Tool.create(name: 'ピントレンズ', image: 'tool_09.png')
Tool.create(name: 'ものしりメガネ', image: 'tool_10.png')
Tool.create(name: 'きあいのハチマキ', image: 'tool_11.png')
Tool.create(name: 'エオスビスケット', image: 'tool_12.png')
Tool.create(name: 'もうこうダンベル', image: 'tool_13.png')
Tool.create(name: 'しんげきメガネ', image: 'tool_14.png')
Tool.create(name: 'たべのこし', image: 'tool_15.png')
Tool.create(name: 'ゴツゴツメット', image: 'tool_16.png')
Tool.create(name: 'するどいツメ', image: 'tool_17.png')
Tool.create(name: 'こだわりメガネ', image: 'tool_18.png')
Tool.create(name: 'じゃくてんほけん', image: 'tool_19.png')

Skill.create(pokemon_id: 1, button: 0, name: 'ヘドロばくだん', image: 'venusaur_skill_1.png', attack_category: 1, level: 5, cool_time: 6, attack_type: '能力低下')
Skill.create(pokemon_id: 1, button: 0, name: 'ギガドレイン', image: 'venusaur_skill_2.png', attack_category: 1, level: 5, cool_time: 7, attack_type: '回復')
Skill.create(pokemon_id: 1, button: 1, name: 'ソーラービーム', image: 'venusaur_skill_3.png', attack_category: 1, level: 7, cool_time: 10, attack_type: '範囲')
Skill.create(pokemon_id: 1, button: 1, name: 'はなびらのまい', image: 'venusaur_skill_4.png', attack_category: 1, level: 7, cool_time: 9, attack_type: '範囲')
Skill.create(pokemon_id: 2, button: 0, name: 'かえんほうしゃ', image: 'charizard_skill_1.png', attack_category: 0, level: 5, cool_time: 5.5, attack_type: '遠隔')
Skill.create(pokemon_id: 2, button: 0, name: 'ほのおのパンチ', image: 'charizard_skill_2.png', attack_category: 0, level: 5, cool_time: 6, attack_type: '近接')
Skill.create(pokemon_id: 2, button: 1, name: 'だいもんじ', image: 'charizard_skill_3.png', attack_category: 0, level: 7, cool_time: 6.5, attack_type: '範囲')
Skill.create(pokemon_id: 2, button: 1, name: 'フレアドライブ', image: 'charizard_skill_4.png', attack_category: 0, level: 7, cool_time: 10, attack_type: '必中')
Skill.create(pokemon_id: 3, button: 0, name: 'ハイドロポンプ', image: 'blastoise_skill_1.png', attack_category: 1, level: 5, cool_time: 8.5, attack_type: '遠隔')
Skill.create(pokemon_id: 3, button: 0, name: 'しおふき', image: 'blastoise_skill_2.png', attack_category: 1, level: 5, cool_time: 7.5, attack_type: '範囲')
Skill.create(pokemon_id: 3, button: 1, name: 'なみのり', image: 'blastoise_skill_3.png', attack_category: 1, level: 7, cool_time: 12, attack_type: 'ムーブ')
Skill.create(pokemon_id: 3, button: 1, name: 'こうそくスピン', image: 'blastoise_skill_4.png', attack_category: 1, level: 7, cool_time: 11, attack_type: '範囲')
Skill.create(pokemon_id: 4, button: 0, name: 'エレキボール', image: 'pikachu_skill_1.png', attack_category: 1, level: 4, cool_time: 5, attack_type: '必中')
Skill.create(pokemon_id: 4, button: 0, name: 'かみなり', image: 'pikachu_skill_2.png', attack_category: 1, level: 4, cool_time: 8, attack_type: '範囲')
Skill.create(pokemon_id: 4, button: 1, name: 'ボルテッカー', image: 'pikachu_skill_3.png', attack_category: 1, level: 6, cool_time: 10, attack_type: '妨害')
Skill.create(pokemon_id: 4, button: 1, name: '10まんボルト', image: 'pikachu_skill_4.png', attack_category: 1, level: 6, cool_time: 8, attack_type: '妨害')
Skill.create(pokemon_id: 5, button: 0, name: 'ゆきなだれ', image: 'alolan-ninetales_skill_1.png', attack_category: 1, level: 4, cool_time: 7, attack_type: '範囲')
Skill.create(pokemon_id: 5, button: 0, name: 'マジカルシャイン', image: 'alolan-ninetales_skill_2.png', attack_category: 1, level: 4, cool_time: 7.5, attack_type: '妨害')
Skill.create(pokemon_id: 5, button: 1, name: 'ふぶき', image: 'alolan-ninetales_skill_3.png', attack_category: 1, level: 6, cool_time: 11, attack_type: '遠隔')
Skill.create(pokemon_id: 5, button: 1, name: 'オーロラベール', image: 'alolan-ninetales_skill_4.png', attack_category: 2, level: 6, cool_time: 13, attack_type: '能力上昇')
Skill.create(pokemon_id: 6, button: 0, name: 'おうふくビンタ', image: 'wigglytuff_skill_1.png', attack_category: 1, level: 6, cool_time: 5, attack_type: '近接')
Skill.create(pokemon_id: 6, button: 0, name: 'マジカルシャイン', image: 'wigglytuff_skill_2.png', attack_category: 1, level: 6, cool_time: 4.5, attack_type: '範囲')
Skill.create(pokemon_id: 6, button: 1, name: 'ころがる', image: 'wigglytuff_skill_3.png', attack_category: 1, level: 4, cool_time: 10, attack_type: '妨害')
Skill.create(pokemon_id: 6, button: 1, name: 'うたう', image: 'wigglytuff_skill_4.png', attack_category: 2, level: 4, cool_time: 10, attack_type: '範囲')
Skill.create(pokemon_id: 7, button: 0, name: 'インファイト', image: 'machamp_skill_1.png', attack_category: 0, level: 7, cool_time: 6, attack_type: '近接')
Skill.create(pokemon_id: 7, button: 0, name: 'クロスチョップ', image: 'machamp_skill_2.png', attack_category: 0, level: 7, cool_time: 6, attack_type: '近接')
Skill.create(pokemon_id: 7, button: 1, name: 'ばくれつパンチ', image: 'machamp_skill_3.png', attack_category: 0, level: 5, cool_time: 8, attack_type: '妨害')
Skill.create(pokemon_id: 7, button: 1, name: 'じごくぐるま', image: 'machamp_skill_4.png', attack_category: 0, level: 5, cool_time: 11, attack_type: '能力上昇')
Skill.create(pokemon_id: 8, button: 0, name: 'ねっとう', image: 'slowbro_skill_1.png', attack_category: 1, level: 4, cool_time: 5, attack_type: '遠隔')
Skill.create(pokemon_id: 8, button: 0, name: 'なみのり', image: 'slowbro_skill_2.png', attack_category: 1, level: 4, cool_time: 9, attack_type: '妨害')
Skill.create(pokemon_id: 8, button: 1, name: 'ドわすれ', image: 'slowbro_skill_3.png', attack_category: 2, level: 6, cool_time: 9, attack_type: '回復')
Skill.create(pokemon_id: 8, button: 1, name: 'テレキネシス', image: 'slowbro_skill_4.png', attack_category: 2, level: 6, cool_time: 11, attack_type: '妨害')
Skill.create(pokemon_id: 9, button: 0, name: 'シャドーボール', image: 'gengar_skill_1.png', attack_category: 1, level: 5, cool_time: 4.5, attack_type: '遠隔')
Skill.create(pokemon_id: 9, button: 0, name: 'ヘドロばくだん', image: 'gengar_skill_2.png', attack_category: 1, level: 5, cool_time: 8, attack_type: '範囲')
Skill.create(pokemon_id: 9, button: 1, name: 'ゆめくい', image: 'gengar_skill_3.png', attack_category: 1, level: 7, cool_time: 8, attack_type: '妨害&ムーブ')
Skill.create(pokemon_id: 9, button: 1, name: 'たたりめ', image: 'gengar_skill_4.png', attack_category: 1, level: 7, cool_time: 7.5, attack_type: 'ムーブ')
Skill.create(pokemon_id: 10, button: 0, name: 'ねんりき', image: 'mr-mime_skill_1.png', attack_category: 1, level: 4, cool_time: 6, attack_type: '遠隔')
Skill.create(pokemon_id: 10, button: 0, name: 'サイコキネシス', image: 'mr-mime_skill_2.png', attack_category: 1, level: 4, cool_time: 6, attack_type: '範囲')
Skill.create(pokemon_id: 10, button: 1, name: 'バリアー', image: 'mr-mime_skill_3.png', attack_category: 2, level: 6, cool_time: 2, attack_type: '妨害')
Skill.create(pokemon_id: 10, button: 1, name: 'ガードスワップ', image: 'mr-mime_skill_4.png', attack_category: 1, level: 6, cool_time: 4.5, attack_type: '能力低下')
Skill.create(pokemon_id: 11, button: 0, name: 'ヘビーボンバー', image: 'snorlax_skill_1.png', attack_category: 0, level: 6, cool_time: 7, attack_type: 'ムーブ')
Skill.create(pokemon_id: 11, button: 0, name: 'じたばた', image: 'snorlax_skill_2.png', attack_category: 0, level: 6, cool_time: 6.5, attack_type: '能力上昇')
Skill.create(pokemon_id: 11, button: 1, name: 'とおせんぼう', image: 'snorlax_skill_3.png', attack_category: 2, level: 8, cool_time: 11, attack_type: '妨害')
Skill.create(pokemon_id: 11, button: 1, name: 'あくび', image: 'snorlax_skill_4.png', attack_category: 2, level: 8, cool_time: 12, attack_type: '妨害')
Skill.create(pokemon_id: 12, button: 0, name: 'タマゴばくだん', image: 'blissey_skill_1.png', attack_category: 1, level: 6, cool_time: 7.5, attack_type: '遠隔')
Skill.create(pokemon_id: 12, button: 0, name: 'てだすけ', image: 'blissey_skill_2.png', attack_category: 2, level: 6, cool_time: 9, attack_type: '能力上昇')
Skill.create(pokemon_id: 12, button: 1, name: 'タマゴうみ', image: 'blissey_skill_3.png', attack_category: 2, level: 4, cool_time: 2, attack_type: '回復')
Skill.create(pokemon_id: 12, button: 1, name: 'しんぴのまもり', image: 'blissey_skill_4.png', attack_category: 2, level: 4, cool_time: 8, attack_type: '能力上昇')
Skill.create(pokemon_id: 13, button: 0, name: 'サイコキネシス', image: 'gardevoir_skill_1.png', attack_category: 1, level: 8, cool_time: 7, attack_type: '遠隔')
Skill.create(pokemon_id: 13, button: 0, name: 'ムーンフォース', image: 'gardevoir_skill_2.png', attack_category: 1, level: 8, cool_time: 6, attack_type: '遠隔')
Skill.create(pokemon_id: 13, button: 1, name: 'サイコショック', image: 'gardevoir_skill_3.png', attack_category: 1, level: 6, cool_time: 10, attack_type: '範囲')
Skill.create(pokemon_id: 13, button: 1, name: 'みらいよち', image: 'gardevoir_skill_4.png', attack_category: 1, level: 6, cool_time: 9, attack_type: '範囲')
Skill.create(pokemon_id: 14, button: 0, name: 'つじぎり', image: 'absol_skill_1.png', attack_category: 0, level: 5, cool_time: 5, attack_type: 'ムーブ')
Skill.create(pokemon_id: 14, button: 0, name: 'おいうち', image: 'absol_skill_2.png', attack_category: 0, level: 5, cool_time: 5, attack_type: 'ムーブ')
Skill.create(pokemon_id: 14, button: 1, name: 'サイコカッター', image: 'absol_skill_3.png', attack_category: 0, level: 7, cool_time: 7, attack_type: '遠隔')
Skill.create(pokemon_id: 14, button: 1, name: 'ふいうち', image: 'absol_skill_4.png', attack_category: 0, level: 7, cool_time: 6, attack_type: '必中')
Skill.create(pokemon_id: 15, button: 0, name: 'あなをほる', image: 'garchomp_skill_1.png', attack_category: 0, level: 6, cool_time: 8, attack_type: 'ムーブ')
Skill.create(pokemon_id: 15, button: 0, name: 'ドラゴンダイブ', image: 'garchomp_skill_2.png', attack_category: 0, level: 6, cool_time: 6, attack_type: 'ムーブ')
Skill.create(pokemon_id: 15, button: 1, name: 'じしん', image: 'garchomp_skill_3.png', attack_category: 0, level: 8, cool_time: 7, attack_type: '範囲')
Skill.create(pokemon_id: 15, button: 1, name: 'ドラゴンクロー', image: 'garchomp_skill_4.png', attack_category: 0, level: 8, cool_time: 5, attack_type: '近接')
Skill.create(pokemon_id: 16, button: 0, name: 'しんそく', image: 'lucario_skill_1.png', attack_category: 0, level: 5, cool_time: 9, attack_type: 'ムーブ')
Skill.create(pokemon_id: 16, button: 0, name: 'グロウパンチ', image: 'lucario_skill_2.png', attack_category: 0, level: 5, cool_time: 7, attack_type: '近接')
Skill.create(pokemon_id: 16, button: 1, name: 'ボーンラッシュ', image: 'lucario_skill_3.png', attack_category: 0, level: 7, cool_time: 10, attack_type: '近接&ムーブ')
Skill.create(pokemon_id: 16, button: 1, name: 'インファイト', image: 'lucario_skill_4.png', attack_category: 0, level: 7, cool_time: 9, attack_type: '近接')
Skill.create(pokemon_id: 17, button: 0, name: 'がんせきふうじ', image: 'crustle_skill_1.png', attack_category: 0, level: 4, cool_time: 5, attack_type: '妨害')
Skill.create(pokemon_id: 17, button: 0, name: 'からをやぶる', image: 'crustle_skill_2.png', attack_category: 2, level: 4, cool_time: 7, attack_type: '能力上昇')
Skill.create(pokemon_id: 17, button: 1, name: 'ステルスロック', image: 'crustle_skill_3.png', attack_category: 0, level: 6, cool_time: 6, attack_type: '範囲')
Skill.create(pokemon_id: 17, button: 1, name: 'シザークロス', image: 'crustle_skill_4.png', attack_category: 0, level: 6, cool_time: 9, attack_type: '近接')
Skill.create(pokemon_id: 18, button: 0, name: 'みずしゅりけん', image: 'greninja_skill_1.png', attack_category: 0, level: 7, cool_time: 5, attack_type: '遠隔')
Skill.create(pokemon_id: 18, button: 0, name: 'なみのり', image: 'greninja_skill_2.png', attack_category: 0, level: 7, cool_time: 9, attack_type: '近接')
Skill.create(pokemon_id: 18, button: 1, name: 'かげぶんしん', image: 'greninja_skill_3.png', attack_category: 2, level: 5, cool_time: 9, attack_type: 'ムーブ')
Skill.create(pokemon_id: 18, button: 1, name: 'えんまく', image: 'greninja_skill_4.png', attack_category: 2, level: 5, cool_time: 13, attack_type: '能力上昇')
Skill.create(pokemon_id: 19, button: 0, name: 'ニトロチャージ', image: 'talonflame_skill_1.png', attack_category: 0, level: 5, cool_time: 6.5, attack_type: 'ムーブ')
Skill.create(pokemon_id: 19, button: 0, name: 'つばめがえし', image: 'talonflame_skill_2.png', attack_category: 0, level: 5, cool_time: 6, attack_type: 'ムーブ')
Skill.create(pokemon_id: 19, button: 1, name: 'そらをとぶ', image: 'talonflame_skill_3.png', attack_category: 0, level: 7, cool_time: 9, attack_type: 'ムーブ')
Skill.create(pokemon_id: 19, button: 1, name: 'ブレイブバード', image: 'talonflame_skill_4.png', attack_category: 0, level: 7, cool_time: 10, attack_type: 'ムーブ')
Skill.create(pokemon_id: 20, button: 0, name: 'ボルトチェンジ', image: 'zeraora_skill_1.png', attack_category: 0, level: 6, cool_time: 8, attack_type: 'ムーブ')
Skill.create(pokemon_id: 20, button: 0, name: 'スパーク', image: 'zeraora_skill_2.png', attack_category: 0, level: 6, cool_time: 10, attack_type: 'ムーブ')
Skill.create(pokemon_id: 20, button: 1, name: 'ほうでん', image: 'zeraora_skill_3.png', attack_category: 0, level: 8, cool_time: 12, attack_type: '範囲')
Skill.create(pokemon_id: 20, button: 1, name: 'ワイルドボルト', image: 'zeraora_skill_4.png', attack_category: 0, level: 8, cool_time: 9, attack_type: '近接')
Skill.create(pokemon_id: 21, button: 0, name: 'かえんボール', image: 'cinderace_skill_1.png', attack_category: 0, level: 7, cool_time: 5, attack_type: '遠隔')
Skill.create(pokemon_id: 21, button: 0, name: 'ブレイズキック', image: 'cinderace_skill_2.png', attack_category: 0, level: 7, cool_time: 8, attack_type: '必中')
Skill.create(pokemon_id: 21, button: 1, name: 'ニトロチャージ', image: 'cinderace_skill_3.png', attack_category: 0, level: 8, cool_time: 5, attack_type: 'ムーブ')
Skill.create(pokemon_id: 21, button: 1, name: 'フェイント', image: 'cinderace_skill_4.png', attack_category: 2, level: 8, cool_time: 13, attack_type: '能力上昇')
Skill.create(pokemon_id: 22, button: 0, name: 'かふんだんご', image: 'eldegoss_skill_1.png', attack_category: 1, level: 4, cool_time: 6, attack_type: '遠隔')
Skill.create(pokemon_id: 22, button: 0, name: 'グラスミキサー', image: 'eldegoss_skill_2.png', attack_category: 1, level: 4, cool_time: 9, attack_type: '遠隔')
Skill.create(pokemon_id: 22, button: 1, name: 'コットンガード', image: 'eldegoss_skill_3.png', attack_category: 2, level: 6, cool_time: 9, attack_type: '能力上昇')
Skill.create(pokemon_id: 22, button: 1, name: 'わたほうし', image: 'eldegoss_skill_4.png', attack_category: 1, level: 6, cool_time: 7.5, attack_type: '範囲')
Skill.create(pokemon_id: 23, button: 0, name: 'なみのり', image: 'cramorant_skill_1.png', attack_category: 1, level: 6, cool_time: 8, attack_type: '遠隔')
Skill.create(pokemon_id: 23, button: 0, name: 'ダイビング', image: 'cramorant_skill_2.png', attack_category: 1, level: 6, cool_time: 1.5, attack_type: 'ムーブ')
Skill.create(pokemon_id: 23, button: 1, name: 'ぼうふう', image: 'cramorant_skill_3.png', attack_category: 1, level: 4, cool_time: 9, attack_type: '妨害')
Skill.create(pokemon_id: 23, button: 1, name: 'エアスラッシュ', image: 'cramorant_skill_4.png', attack_category: 1, level: 4, cool_time: 5, attack_type: '遠隔')
Skill.create(pokemon_id: 24, button: 0, name: 'つららおとし', image: 'mamoswine_skill_1.png', attack_category: 0, level: 6, cool_time: 10, attack_type: '妨害')
Skill.create(pokemon_id: 24, button: 0, name: 'こおりのキバ', image: 'mamoswine_skill_2.png', attack_category: 0, level: 6, cool_time: 8, attack_type: '妨害')
Skill.create(pokemon_id: 24, button: 1, name: '10まんばりき', image: 'mamoswine_skill_3.png', attack_category: 0, level: 8, cool_time: 8, attack_type: 'ムーブ')
Skill.create(pokemon_id: 24, button: 1, name: 'じしん', image: 'mamoswine_skill_4.png', attack_category: 0, level: 8, cool_time: 7.5, attack_type: 'ムーブ')
Skill.create(pokemon_id: 25, button: 0, name: 'マジカルフレイム', image: 'sylveon_skill_1.png', attack_category: 1, level: 4, cool_time: 7, attack_type: 'ムーブ')
Skill.create(pokemon_id: 25, button: 0, name: 'ハイパーボイス', image: 'sylveon_skill_2.png', attack_category: 1, level: 4, cool_time: 5, attack_type: '範囲')
Skill.create(pokemon_id: 25, button: 1, name: 'ドレインキッス', image: 'sylveon_skill_3.png', attack_category: 1, level: 6, cool_time: 10, attack_type: '必中')
Skill.create(pokemon_id: 25, button: 1, name: 'めいそう', image: 'sylveon_skill_4.png', attack_category: 2, level: 6, cool_time: 10, attack_type: '能力上昇')
Skill.create(pokemon_id: 26, button: 0, name: 'タネマシンガン', image: 'greedent_skill_1.png', attack_category: 0, level: 7, cool_time: 5, attack_type: '遠隔')
Skill.create(pokemon_id: 26, button: 0, name: 'ゲップ', image: 'greedent_skill_2.png', attack_category: 0, level: 7, cool_time: 5, attack_type: '遠隔')
Skill.create(pokemon_id: 26, button: 1, name: 'ほおばる', image: 'greedent_skill_3.png', attack_category: 2, level: 5, cool_time: 8, attack_type: '能力上昇')
Skill.create(pokemon_id: 26, button: 1, name: 'ほしがる', image: 'greedent_skill_4.png', attack_category: 0, level: 5, cool_time: 9, attack_type: '妨害')

User.create(name: 'Sylpha', email: 'sylpha.games@gmail.com', password: 'sayumi729864')

Pokemon.order(id: :asc).each do |pokemon|
  Stage.order(id: :asc).each do |stage|
    Score.create(user_id: 1, pokemon_id: pokemon.id, stage_id: stage.id)
  end
end

MySet.create(user_id: 1, pokemon_id: 1, r_skill_id: 2, zr_skill_id: 4, battle_item_id: 5, tool_1_id: 5, tool_2_id: 10, tool_3_id: 2)
MySet.create(user_id: 1, pokemon_id: 2, r_skill_id: 5, zr_skill_id: 7, battle_item_id: 5, tool_1_id: 5, tool_2_id: 11, tool_3_id: 1)
MySet.create(user_id: 1, pokemon_id: 3, r_skill_id: 10, zr_skill_id: 12, battle_item_id: 5, tool_1_id: 5, tool_2_id: 11, tool_3_id: 6)
MySet.create(user_id: 1, pokemon_id: 4, r_skill_id: 13, zr_skill_id: 16, battle_item_id: 5, tool_1_id: 5, tool_2_id: 10, tool_3_id: 2)
MySet.create(user_id: 1, pokemon_id: 5, r_skill_id: 18, zr_skill_id: 20, battle_item_id: 5, tool_1_id: 5, tool_2_id: 10, tool_3_id: 2)
MySet.create(user_id: 1, pokemon_id: 6, r_skill_id: 22, zr_skill_id: 24, battle_item_id: 5, tool_1_id: 5, tool_2_id: 11, tool_3_id: 6)
MySet.create(user_id: 1, pokemon_id: 7, r_skill_id: 26, zr_skill_id: 28, battle_item_id: 5, tool_1_id: 5, tool_2_id: 11, tool_3_id: 1)
MySet.create(user_id: 1, pokemon_id: 8, r_skill_id: 29, zr_skill_id: 31, battle_item_id: 5, tool_1_id: 5, tool_2_id: 11, tool_3_id: 6)
MySet.create(user_id: 1, pokemon_id: 9, r_skill_id: 33, zr_skill_id: 35, battle_item_id: 5, tool_1_id: 5, tool_2_id: 10, tool_3_id: 2)
MySet.create(user_id: 1, pokemon_id: 10, r_skill_id: 37, zr_skill_id: 40, battle_item_id: 5, tool_1_id: 5, tool_2_id: 11, tool_3_id: 6)
MySet.create(user_id: 1, pokemon_id: 11, r_skill_id: 42, zr_skill_id: 44, battle_item_id: 5, tool_1_id: 5, tool_2_id: 11, tool_3_id: 6)
MySet.create(user_id: 1, pokemon_id: 12, r_skill_id: 45, zr_skill_id: 47, battle_item_id: 5, tool_1_id: 5, tool_2_id: 11, tool_3_id: 6)
MySet.create(user_id: 1, pokemon_id: 13, r_skill_id: 50, zr_skill_id: 51, battle_item_id: 5, tool_1_id: 5, tool_2_id: 10, tool_3_id: 2)
MySet.create(user_id: 1, pokemon_id: 14, r_skill_id: 54, zr_skill_id: 55, battle_item_id: 5, tool_1_id: 5, tool_2_id: 11, tool_3_id: 1)
MySet.create(user_id: 1, pokemon_id: 15, r_skill_id: 57, zr_skill_id: 59, battle_item_id: 5, tool_1_id: 5, tool_2_id: 11, tool_3_id: 1)
MySet.create(user_id: 1, pokemon_id: 16, r_skill_id: 62, zr_skill_id: 64, battle_item_id: 5, tool_1_id: 5, tool_2_id: 11, tool_3_id: 1)
MySet.create(user_id: 1, pokemon_id: 17, r_skill_id: 66, zr_skill_id: 67, battle_item_id: 5, tool_1_id: 5, tool_2_id: 11, tool_3_id: 6)
MySet.create(user_id: 1, pokemon_id: 18, r_skill_id: 69, zr_skill_id: 71, battle_item_id: 5, tool_1_id: 5, tool_2_id: 11, tool_3_id: 1)
MySet.create(user_id: 1, pokemon_id: 19, r_skill_id: 73, zr_skill_id: 75, battle_item_id: 5, tool_1_id: 5, tool_2_id: 11, tool_3_id: 1)
MySet.create(user_id: 1, pokemon_id: 20, r_skill_id: 77, zr_skill_id: 79, battle_item_id: 5, tool_1_id: 5, tool_2_id: 11, tool_3_id: 1)
MySet.create(user_id: 1, pokemon_id: 21, r_skill_id: 81, zr_skill_id: 83, battle_item_id: 5, tool_1_id: 5, tool_2_id: 11, tool_3_id: 1)
MySet.create(user_id: 1, pokemon_id: 22, r_skill_id: 86, zr_skill_id: 87, battle_item_id: 5, tool_1_id: 5, tool_2_id: 11, tool_3_id: 6)
MySet.create(user_id: 1, pokemon_id: 23, r_skill_id: 89, zr_skill_id: 91, battle_item_id: 5, tool_1_id: 5, tool_2_id: 10, tool_3_id: 2)
MySet.create(user_id: 1, pokemon_id: 24, r_skill_id: 93, zr_skill_id: 95, battle_item_id: 5, tool_1_id: 5, tool_2_id: 11, tool_3_id: 6)
MySet.create(user_id: 1, pokemon_id: 25, r_skill_id: 98, zr_skill_id: 100, battle_item_id: 5, tool_1_id: 5, tool_2_id: 10, tool_3_id: 2)
MySet.create(user_id: 1, pokemon_id: 26, r_skill_id: 102, zr_skill_id: 103, battle_item_id: 5, tool_1_id: 5, tool_2_id: 11, tool_3_id: 6)
