Pokemon.create(name: 'フシギバナ', image: 'venusaur.png', attack_type: 1, role: 0, attack_category: 1)
Pokemon.create(name: 'リザードン', image: 'charizard.png', attack_type: 0, role: 3, attack_category: 0)
Pokemon.create(name: 'カメックス', image: 'blastoise.png', attack_type: 1, role: 1, attack_category: 1)
Pokemon.create(name: 'ピカチュウ', image: 'pikachu.png', attack_type: 1, role: 0, attack_category: 1)
Pokemon.create(name: 'アローラキュウコン', image: 'alolan-ninetales.png', attack_type: 1, role: 0, attack_category: 1)
Pokemon.create(name: 'プクリン', image: 'wigglytuff.png', attack_type: 0, role: 4, attack_category: 1)
Pokemon.create(name: 'カイリキー', image: 'machamp.png', attack_type: 0, role: 3, attack_category: 0)
Pokemon.create(name: 'ヤドラン', image: 'slowbro.png', attack_type: 1, role: 1, attack_category: 1)
Pokemon.create(name: 'ゲンガー', image: 'gengar.png', attack_type: 0, role: 2, attack_category: 1)
Pokemon.create(name: 'バリヤード', image: 'mr-mime.png', attack_type: 0, role: 4, attack_category: 1)
Pokemon.create(name: 'カビゴン', image: 'snorlax.png', attack_type: 0, role: 1, attack_category: 0)
Pokemon.create(name: 'ハピナス', image: 'blissey.png', attack_type: 0, role: 4, attack_category: 1)
Pokemon.create(name: 'サーナイト', image: 'gardevoir.png', attack_type: 1, role: 0, attack_category: 1)
Pokemon.create(name: 'アブソル', image: 'absol.png', attack_type: 0, role: 2, attack_category: 0)
Pokemon.create(name: 'ガブリアス', image: 'garchomp.png', attack_type: 0, role: 3, attack_category: 0)
Pokemon.create(name: 'ルカリオ', image: 'lucario.png', attack_type: 0, role: 3, attack_category: 0)
Pokemon.create(name: 'イワパレス', image: 'crustle.png', attack_type: 0, role: 1, attack_category: 0)
Pokemon.create(name: 'ゲッコウガ', image: 'greninja.png', attack_type: 1, role: 0, attack_category: 0)
Pokemon.create(name: 'ファイアロー', image: 'talonflame.png', attack_type: 0, role: 2, attack_category: 0)
Pokemon.create(name: 'ゼラオラ', image: 'zeraora.png', attack_type: 0, role: 2, attack_category: 0)
Pokemon.create(name: 'エースバーン', image: 'cinderace.png', attack_type: 1, role: 0, attack_category: 0)
Pokemon.create(name: 'ワタシラガ', image: 'eldegoss.png', attack_type: 1, role: 4, attack_category: 1)
Pokemon.create(name: 'ウッウ', image: 'cramorant.png', attack_type: 1, role: 0, attack_category: 1)

Stage.create(name: 'レモータスタジアム', image: 'remoat_stadium.jpg')
Stage.create(name: 'ジーヴルシティ', image: 'shivre_city.jpg')
Stage.create(name: 'マールスタジアム', image: 'mer_stadium.jpg')
Stage.create(name: 'ゼフィオパーク', image: 'auroma_park.jpg')

BattleItem.create(name: 'キズぐすり', image: 'battle_item_1.png')
BattleItem.create(name: 'プラスパワー', image: 'battle_item_2.png')
BattleItem.create(name: 'スピーダー', image: 'battle_item_3.png')
BattleItem.create(name: 'エネコのしっぽ', image: 'battle_item_4.png')
BattleItem.create(name: 'だっしゅつボタン', image: 'battle_item_5.png')
BattleItem.create(name: 'どんそくスモーク', image: 'battle_item_6.png')
BattleItem.create(name: 'なんでもなおし', image: 'battle_item_7.png')
BattleItem.create(name: 'ゴールかそくそうち', image: 'battle_item_8.png')

Tool.create(name: 'ピントレンズ', image: 'tool_1.png')
Tool.create(name: 'ちからのハチマキ', image: 'tool_2.png')
Tool.create(name: 'かるいし', image: 'tool_3.png')
Tool.create(name: 'かいがらのすず', image: 'tool_4.png')
Tool.create(name: 'ものしりメガネ', image: 'tool_5.png')
Tool.create(name: 'きあいのハチマキ', image: 'tool_6.png')
Tool.create(name: 'おたすけバリア', image: 'tool_7.png')
Tool.create(name: 'ゴツゴツメット', image: 'tool_8.png')
Tool.create(name: 'がくしゅうそうち', image: 'tool_9.png')
Tool.create(name: 'たべのこし', image: 'tool_10.png')
Tool.create(name: 'とつげきチョッキ', image: 'tool_11.png')
Tool.create(name: 'ゴールサポーター', image: 'tool_12.png')
Tool.create(name: 'エナジーアンプ', image: 'tool_13.png')
Tool.create(name: 'エオスビスケット', image: 'tool_14.png')
Tool.create(name: 'もうこうダンベル', image: 'tool_15.png')
Tool.create(name: 'しんげきメガネ', image: 'tool_16.png')

User.create(name: 'Sylpha', email: 'sylpha.games@gmail.com', password: 'sayumi729864')
